### ISSUE TITLE
Ownership and maintenance of the aws-naip s3 bucket

### ISSUE THREAD

**Issue by robert-claypool** [mapbox/s3pay#1]
Unlike the `landsat-pds` bucket and other [AWS Public Datasets](https://aws.amazon.com/public-data-sets/), there is little information online about `aws-naip`. Is it an official bucket? Who owns it?

**Comment by jedsundwall** [comment]
@robert-claypool A few of us at AWS maintain `s3://aws-naip` for our own internal testing and demo purposes. We're happy to let others use it but don't make any guarantees about its availability or the data in it.

**Comment by andrewljohnson** [comment]
@jedsundwall I am trying to use these naips for this project: https://github.com/trailbehind/DeepOSM

I am able to download one NAIP, but I can't figure out how to list the files of the bucket with boto or the aws CLI. Any pointers on how to enumerate the files?

**Comment by robert-claypool** [comment]
@andrewljohnson I have not tested this, but apparently you can mount the bucket using danilop/yas3fs. See https://gist.github.com/mwkorver/1ef45abac3871360f2b1

You are right that object listing is disabled; compare to `landsat-pds`...

``` shell
$ aws s3 ls s3://aws-naip
A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied

$ aws s3 ls s3://landsat-pds
                           PRE L8/
                           PRE landsat-pds_stats/
2015-01-28 12:13:53      23764 index.html
```

@jedsundwall please grant List permissions on this bucket for Everyone if possible.

**Comment by andrewljohnson** [comment]
@robert-claypool @jedsundwall FWIW, I was able to enumerate the files with s3cmd 1.6.0, but not aws CLI or boto. It'd be cool if it worked in boto so I don't have to subprocess s3cmd.

```
s3cmd ls --recursive --skip-existing s3://aws-naip/md/2013/1m/rgbir/ --requester-pays
```
